version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/aivle-backend

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/cleanup.sh
      timeout: 60
      runas: ubuntu

  AfterInstall:
    - location: scripts/install.sh
      timeout: 60
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start.sh
      timeout: 60
      runas: ubuntu

  ValidateService:
    - location: scripts/validate.sh
      timeout: 60
      runas: ubuntu
